[2025-04-16T12:59:51.535+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-16T12:59:52.732+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: beer_data_processing.create_dim_brewery scheduled__2025-04-11T00:00:00+00:00 [queued]>
[2025-04-16T12:59:52.954+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: beer_data_processing.create_dim_brewery scheduled__2025-04-11T00:00:00+00:00 [queued]>
[2025-04-16T12:59:52.984+0000] {taskinstance.py:2867} INFO - Starting attempt 3 of 6
[2025-04-16T12:59:53.362+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): create_dim_brewery> on 2025-04-11 00:00:00+00:00
[2025-04-16T12:59:54.828+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'beer_data_processing', 'create_dim_brewery', 'scheduled__2025-04-11T00:00:00+00:00', '--job-id', '390', '--raw', '--subdir', 'DAGS_FOLDER/beer_data_processing_dag.py', '--cfg-path', '/tmp/tmptjbttinp']
[2025-04-16T12:59:54.908+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=2747) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-04-16T12:59:55.004+0000] {standard_task_runner.py:72} INFO - Started process 2907 to run task
[2025-04-16T12:59:55.001+0000] {standard_task_runner.py:105} INFO - Job 390: Subtask create_dim_brewery
[2025-04-16T12:59:57.608+0000] {task_command.py:467} INFO - Running <TaskInstance: beer_data_processing.create_dim_brewery scheduled__2025-04-11T00:00:00+00:00 [running]> on host 3e53738720c8
[2025-04-16T13:00:02.547+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='beer_data_processing' AIRFLOW_CTX_TASK_ID='create_dim_brewery' AIRFLOW_CTX_EXECUTION_DATE='2025-04-11T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-11T00:00:00+00:00'
[2025-04-16T13:00:02.431+0000] {job.py:229} INFO - Heartbeat recovered after 14.59 seconds
[2025-04-16T13:00:03.272+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-04-16T13:00:03.534+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-04-16T13:00:05.229+0000] {logging_mixin.py:190} INFO - Current task name:create_dim_brewery state:running start_date:2025-04-16 12:59:52.802945+00:00
[2025-04-16T13:00:05.750+0000] {logging_mixin.py:190} INFO - Dag name:beer_data_processing and current dag run status:running
[2025-04-16T13:00:06.451+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-04-16T13:00:32.678+0000] {job.py:229} INFO - Heartbeat recovered after 30.50 seconds
[2025-04-16T13:00:46.392+0000] {job.py:229} INFO - Heartbeat recovered after 14.00 seconds
[2025-04-16T13:00:48.777+0000] {base.py:84} INFO - Retrieving connection 'postgres_conn'
[2025-04-16T13:00:59.992+0000] {logging_mixin.py:190} INFO - Створено датасет dim_brewery з 4000 записами
[2025-04-16T13:01:00.721+0000] {python.py:240} INFO - Done. Returned value was: True
[2025-04-16T13:01:02.277+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-04-16T13:01:02.318+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=beer_data_processing, task_id=create_dim_brewery, run_id=scheduled__2025-04-11T00:00:00+00:00, execution_date=20250411T000000, start_date=20250416T125952, end_date=20250416T130102
[2025-04-16T13:01:03.829+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2025-04-16T13:01:03.870+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2025-04-16T13:01:03.891+0000] {logging_mixin.py:190} INFO - Dag name:beer_data_processing queued_at:2025-04-16 12:41:28.007590+00:00
[2025-04-16T13:01:03.978+0000] {logging_mixin.py:190} INFO - Task hostname:3e53738720c8 operator:PythonOperator
[2025-04-16T13:01:04.592+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-04-16T13:01:07.474+0000] {taskinstance.py:3901} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-04-16T13:01:08.086+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-04-16T13:01:09.441+0000] {standard_task_runner.py:217} INFO - Process not found (most likely exited), stop collecting metrics
