[2025-04-09T21:45:41.531+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-09T21:45:41.582+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: beer_data_processing.create_tables manual__2025-04-09T21:45:02.207977+00:00 [queued]>
[2025-04-09T21:45:41.612+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: beer_data_processing.create_tables manual__2025-04-09T21:45:02.207977+00:00 [queued]>
[2025-04-09T21:45:41.614+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-04-09T21:45:41.652+0000] {taskinstance.py:2890} INFO - Executing <Task(SQLExecuteQueryOperator): create_tables> on 2025-04-09 21:45:02.207977+00:00
[2025-04-09T21:45:41.679+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'beer_data_processing', 'create_tables', 'manual__2025-04-09T21:45:02.207977+00:00', '--job-id', '67', '--raw', '--subdir', 'DAGS_FOLDER/beer_data_processing_dag.py', '--cfg-path', '/tmp/tmpnjn06e0p']
[2025-04-09T21:45:41.683+0000] {standard_task_runner.py:105} INFO - Job 67: Subtask create_tables
[2025-04-09T21:45:41.685+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=28903) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-04-09T21:45:41.687+0000] {standard_task_runner.py:72} INFO - Started process 29073 to run task
[2025-04-09T21:45:41.786+0000] {task_command.py:467} INFO - Running <TaskInstance: beer_data_processing.create_tables manual__2025-04-09T21:45:02.207977+00:00 [running]> on host 893b969cc7b0
[2025-04-09T21:45:41.985+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='beer_data_processing' AIRFLOW_CTX_TASK_ID='create_tables' AIRFLOW_CTX_EXECUTION_DATE='2025-04-09T21:45:02.207977+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-09T21:45:02.207977+00:00'
[2025-04-09T21:45:41.989+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-04-09T21:45:41.991+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-04-09T21:45:41.993+0000] {logging_mixin.py:190} INFO - Current task name:create_tables state:running start_date:2025-04-09 21:45:41.583999+00:00
[2025-04-09T21:45:41.994+0000] {logging_mixin.py:190} INFO - Dag name:beer_data_processing and current dag run status:running
[2025-04-09T21:45:41.996+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-04-09T21:45:41.998+0000] {sql.py:295} INFO - Executing: 
    -- Створення таблиці dim_beer
    CREATE TABLE IF NOT EXISTS dim_beer (
        beer_id INTEGER PRIMARY KEY,
        beer_name VARCHAR(255) NOT NULL
    );
    
    -- Створення таблиці dim_style
    CREATE TABLE IF NOT EXISTS dim_style (
        style_id INTEGER PRIMARY KEY,
        style_name VARCHAR(255) NOT NULL
    );
    
    -- Створення таблиці dim_brewery
    CREATE TABLE IF NOT EXISTS dim_brewery (
        brewery_id INTEGER PRIMARY KEY,
        brewery_name VARCHAR(255) NOT NULL
    );
    
    -- Створення таблиці фактів
    CREATE TABLE IF NOT EXISTS fact_beer (
        beer_id INTEGER REFERENCES dim_beer(beer_id),
        style_id INTEGER REFERENCES dim_style(style_id),
        brewery_id INTEGER REFERENCES dim_brewery(brewery_id),
        abv FLOAT,
        min_ibu FLOAT,
        max_ibu FLOAT,
        astringency FLOAT,
        body FLOAT,
        alcohol FLOAT,
        bitter FLOAT,
        sweet FLOAT,
        sour FLOAT,
        salty FLOAT,
        fruits FLOAT,
        hoppy FLOAT,
        spices FLOAT,
        malty FLOAT,
        average_review_overall NUMERIC(3,2),
        number_of_reviews INTEGER,
        PRIMARY KEY (beer_id, style_id, brewery_id)
    );
    
[2025-04-09T21:45:42.043+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 296, in execute
    hook = self.get_db_hook()
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 195, in get_db_hook
    return self._hook
           ^^^^^^^^^^
  File "/usr/local/lib/python3.12/functools.py", line 998, in __get__
    val = self.func(instance)
          ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 171, in _hook
    hook = self.get_hook(conn_id=conn_id, hook_params=self.hook_params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 163, in get_hook
    connection = BaseHook.get_connection(conn_id)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/hooks/base.py", line 83, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py", line 537, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `postgres_conn` isn't defined
[2025-04-09T21:45:42.068+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-04-09T21:45:42.070+0000] {logging_mixin.py:190} INFO - Task start:2025-04-09 21:45:41.583999+00:00 end:2025-04-09 21:45:42.067645+00:00 duration:0.483646
[2025-04-09T21:45:42.071+0000] {logging_mixin.py:190} INFO - Task:<Task(SQLExecuteQueryOperator): create_tables> dag:<DAG: beer_data_processing> dagrun:<DagRun beer_data_processing @ 2025-04-09 21:45:02.207977+00:00: manual__2025-04-09T21:45:02.207977+00:00, state:running, queued_at: 2025-04-09 21:45:03.285545+00:00. externally triggered: True>
[2025-04-09T21:45:42.072+0000] {logging_mixin.py:190} INFO - Failure caused by The conn_id `postgres_conn` isn't defined
[2025-04-09T21:45:42.073+0000] {taskinstance.py:1226} INFO - Marking task as FAILED. dag_id=beer_data_processing, task_id=create_tables, run_id=manual__2025-04-09T21:45:02.207977+00:00, execution_date=20250409T214502, start_date=20250409T214541, end_date=20250409T214542
[2025-04-09T21:45:42.134+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-04-09T21:45:42.135+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 67 for task create_tables (The conn_id `postgres_conn` isn't defined; 29073)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 296, in execute
    hook = self.get_db_hook()
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 195, in get_db_hook
    return self._hook
           ^^^^^^^^^^
  File "/usr/local/lib/python3.12/functools.py", line 998, in __get__
    val = self.func(instance)
          ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 171, in _hook
    hook = self.get_hook(conn_id=conn_id, hook_params=self.hook_params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 163, in get_hook
    connection = BaseHook.get_connection(conn_id)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/hooks/base.py", line 83, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py", line 537, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `postgres_conn` isn't defined
[2025-04-09T21:45:42.190+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-04-09T21:45:42.255+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-09T21:45:42.265+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
