[2025-04-10T13:38:32.195+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-10T13:38:32.243+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: beer_data_processing.create_dim_beer manual__2025-04-10T13:36:07.917582+00:00 [queued]>
[2025-04-10T13:38:32.266+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: beer_data_processing.create_dim_beer manual__2025-04-10T13:36:07.917582+00:00 [queued]>
[2025-04-10T13:38:32.267+0000] {taskinstance.py:2867} INFO - Starting attempt 4 of 6
[2025-04-10T13:38:32.295+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): create_dim_beer> on 2025-04-10 13:36:07.917582+00:00
[2025-04-10T13:38:32.320+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'beer_data_processing', 'create_dim_beer', 'manual__2025-04-10T13:36:07.917582+00:00', '--job-id', '290', '--raw', '--subdir', 'DAGS_FOLDER/beer_data_processing_dag.py', '--cfg-path', '/tmp/tmp57wwoq8p']
[2025-04-10T13:38:32.326+0000] {standard_task_runner.py:105} INFO - Job 290: Subtask create_dim_beer
[2025-04-10T13:38:32.329+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=10850) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-04-10T13:38:32.332+0000] {standard_task_runner.py:72} INFO - Started process 10904 to run task
[2025-04-10T13:38:32.449+0000] {task_command.py:467} INFO - Running <TaskInstance: beer_data_processing.create_dim_beer manual__2025-04-10T13:36:07.917582+00:00 [running]> on host 3e53738720c8
[2025-04-10T13:38:32.668+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='beer_data_processing' AIRFLOW_CTX_TASK_ID='create_dim_beer' AIRFLOW_CTX_EXECUTION_DATE='2025-04-10T13:36:07.917582+00:00' AIRFLOW_CTX_TRY_NUMBER='4' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-10T13:36:07.917582+00:00'
[2025-04-10T13:38:32.672+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-04-10T13:38:32.674+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-04-10T13:38:32.675+0000] {logging_mixin.py:190} INFO - Current task name:create_dim_beer state:running start_date:2025-04-10 13:38:32.245264+00:00
[2025-04-10T13:38:32.677+0000] {logging_mixin.py:190} INFO - Dag name:beer_data_processing and current dag run status:running
[2025-04-10T13:38:32.678+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-04-10T13:38:32.828+0000] {base.py:84} INFO - Retrieving connection 'postgres_conn'
[2025-04-10T13:38:34.335+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/beer_data_processing_dag.py", line 126, in populate_dim_beer
    return populate_dim_table('Name', 'dim_beer', 'beer', **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/beer_data_processing_dag.py", line 97, in populate_dim_table
    cursor.execute(
psycopg2.errors.StringDataRightTruncation: value too long for type character varying(255)

[2025-04-10T13:38:34.382+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-04-10T13:38:34.383+0000] {logging_mixin.py:190} INFO - Task start:2025-04-10 13:38:32.245264+00:00 end:2025-04-10 13:38:34.379834+00:00 duration:2.13457
[2025-04-10T13:38:34.385+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): create_dim_beer> dag:<DAG: beer_data_processing> dagrun:<DagRun beer_data_processing @ 2025-04-10 13:36:07.917582+00:00: manual__2025-04-10T13:36:07.917582+00:00, state:running, queued_at: 2025-04-10 13:36:08.187437+00:00. externally triggered: True>
[2025-04-10T13:38:34.386+0000] {logging_mixin.py:190} INFO - Failure caused by value too long for type character varying(255)
[2025-04-10T13:38:34.386+0000] {taskinstance.py:1226} INFO - Marking task as UP_FOR_RETRY. dag_id=beer_data_processing, task_id=create_dim_beer, run_id=manual__2025-04-10T13:36:07.917582+00:00, execution_date=20250410T133607, start_date=20250410T133832, end_date=20250410T133834
[2025-04-10T13:38:34.458+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-04-10T13:38:34.459+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 290 for task create_dim_beer (value too long for type character varying(255)
; 10904)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/beer_data_processing_dag.py", line 126, in populate_dim_beer
    return populate_dim_table('Name', 'dim_beer', 'beer', **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/beer_data_processing_dag.py", line 97, in populate_dim_table
    cursor.execute(
psycopg2.errors.StringDataRightTruncation: value too long for type character varying(255)

[2025-04-10T13:38:34.521+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-04-10T13:38:34.578+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-10T13:38:34.582+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
